version: '3.8'

services: 
  django-spa-compose:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - spa_data:/home/app/webapp
    ports:
      - 8000:8000
 
volumes:
  spa_data: